@url = http://localhost:5000
@stateId = 774ce13b-3f77-4918-a14d-333111f53d7a
@userId = 3912657e-df36-40c0-893d-2be8ad374109



###
# @name sign_in
POST {{url}}/users/sign-in
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin@123"
}

###
@accessToken = {{sign_in.response.body.$.accessToken}}


###
GET {{url}}/users

###
GET {{url}}/users/{{userId}}


###
GET {{url}}/users/me
Authorization: Bearer {{accessToken}}

###
GET {{url}}/users/roles
Authorization: Bearer {{accessToken}}

###
POST {{url}}/users
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "fullName": "state-admin",
    "email": "state-admin@kmcc.com",
    "mobileNumber": "0501234123",
    "alternativeContactNumber": "0501234123",
    "designation": "state admin",
    "role": "state-admin",
    "cascadeId": "3472B53D-0EF9-4251-B291-190B35CD280B"
}

###
GET {{url}}/lookups

###
GET {{url}}/lookups/me
Authorization: Bearer {{accessToken}}

###
GET {{url}}/states

###
GET {{url}}/states/{{stateId}}

###
POST {{url}}/states
Content-Type: application/json

{
    "name": "New State 12"
}

###
PUT  {{url}}/states/{{stateId}}
Content-Type: application/json

{
    "name": "FUJAIRAH -"
}

###
DELETE {{url}}/states/{{stateId}}

###
GET {{url}}/area

###
GET {{url}}/area/{{stateId}}

###
POST   {{url}}/members
Content-Type: application/json

{
    "fullName": "Muhammed Rafi",
    "emiratesIdNumber": "784-1975-5494627-3",
    "emiratesIdExpiry": "2023-08-15",
    "emiratesIdFrontPage": null,
    "emiratesIdLastPage": null,
    "DateOfBirth": "1975-03-04",
    "mobileNumber": "0554296326",
    "alternativeContactNumber": "0501114111",
    "email": "test@test.com",
    "passportNumber": "2322323",
    "passportExpiry": "2024-02-02",
    "passportFrontPage": null,
    "passportLastPage": null,
    "professionId" : "150c5a51-cd2e-4021-8afc-e0767420dca7",
    "qualificationId": "12cedccf-b2f0-4cd5-91a7-ad64464cdd90",
    "bloodGroup": 0,
    "photo": "",
    "houseName": "Goush",
    "addressInIndia": "Thakwa Nagar",
    "passwordHash": "123",
    "areaId": "9073BB7B-5E09-4FD7-80A4-1D874BC78DC3",
    "mandalamId": "", 
    "isMemberOfAnyIndianRegisteredOrganization": true,
    "isKMCCWelfareScheme": true
}