@url = http://localhost:5000
@userId = 3912657e-df36-40c0-893d-2be8ad374109
@requestId = a28acf6b-a270-4182-b5f9-bb736dccbdaa
@areaId = 97856452-46ee-4a51-a6c9-dfc065ec73dd
@mandalamId = 30BA1C7F-4BD7-43D9-9F62-07C377FEB667
@stateId = 30BA1C7F-4BD7-43D9-9F62-07C377FEB667

###
# @name sign_in
POST {{url}}/users/sign-in
Content-Type: application/json

{
    "email": "dispute-committee@admin.com",
    "password": "admin@123"
}

###
@accessToken = {{sign_in.response.body.$.accessToken}}


###
GET {{url}}/disputes

###
GET {{url}}/disputes/{{requestId}}

###
GET {{url}}/disputes/role
Authorization: Bearer {{accessToken}}

###
GET {{url}}/disputes/area/{{areaId}}

###
GET {{url}}/disputes/mandalam/{{mandalamId}}

###
GET {{url}}/disputes/state/{{stateId}}

###
POST {{url}}/disputes
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "memberId": "0cdacc2d-3043-48e6-94b3-4757b7b50270",
    "toAreaId": "43ffa5c5-1d27-482c-8e67-40069afb92a4",
    "toPanchayatId": "4e14ac81-5462-4c3c-afe8-001af60182c9",
    "reason": "test"
}
