@url = http://localhost:5000
@mandalamId = 3912657e-df36-40c0-893d-2be8ad374109
@districtId = cf5e40d1-6f85-4540-9cb6-5ad7d7980141



###
# @name sign_in
POST {{url}}/users/sign-in
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin@123"
}

###
@accessToken = {{sign_in.response.body.$.accessToken}}


###
GET {{url}}/mandalams

###
GET {{url}}/mandalams/{{mandalamId}}

###
GET {{url}}/mandalams/district/{{districtId}}

####
POST {{url}}/mandalams
Content-Type: application/json

{
    "name": "New Mandalam",
    "sateId": {{districtId}}
}

###
PUT  {{url}}/mandalams/{{mandalamId}}
Content-Type: application/json

{
    "name": "Mandalam name changed",
    "districtId": {{districtId}}
}

###
DELETE {{url}}/mandalams/{{mandalamId}}