@url = http://localhost:5000
@memberId = 354c1baf-cad9-4392-bf85-7a843cc161c1
@districtId = 30BA1C7F-4BD7-43D9-9F62-07C377FEB667


###
# @name sign_in
POST {{url}}/users/sign-in
Content-Type: application/json

{
    "email": "mandalam-agent@admin.com",
    "password": "admin@123"
}

###
@accessToken = {{sign_in.response.body.$.accessToken}}


###
GET {{url}}/members

###
GET {{url}}/members/{{memberId}}

###
GET {{url}}/members/role
Authorization: Bearer {{accessToken}}

###
POST {{url}}/members
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "fullName":"Muhammed Sameer Ceetheerakath",
    "emiratesIdNumber":"784-1975-0750835-2",
    "emiratesIdExpiry":"2024-01-08",
    "emiratesIdFrontPage":"30f601e2-b615-44e5-b124-1d5c3e0d32fc",
    "emiratesIdLastPage":"ead090b2-ccfc-4b04-be58-b45c5fee0ffc",
    "dateOfBirth":"1975-04-10",
    "mobileNumber":"0554296326",
    "email":"rafi.genius.cs@gmail.com",
    "passportNumber":"4353453",
    "passportExpiry":"2022-08-11",
    "passportFrontPage":"",
    "passportLastPage":"",
    "professionId":"f5e3c868-84e8-47b6-a5ed-c7c491258fe4",
    "qualificationId":"45e7f4c7-4551-463a-89ba-460602c4ee81",
    "bloodGroup":"0",
    "gender":"0",
    "photo":"",
    "houseName":"GG",
    "addressInIndia":"test",
    "addressInDistrictId":"a945211d-4d57-451b-9feb-a4585138df82",
    "addressInMandalamId":"86ecb0fc-5d66-4ebb-abce-15895db10f2c",
    "addressInPanchayatId":"422e0bfa-e3cb-4c63-b94a-b11f308e6567",
    "areaId":"97856452-46ee-4a51-a6c9-dfc065ec73dd",
    "panchayatId":"1bf4974b-b70a-4314-ab82-9adff66be809",
    "mandalamId":"86ecb0fc-5d66-4ebb-abce-15895db10f2c",
    "registeredOrganizationId":"a78b37ba-6a3e-4dc5-88f5-2040c66acc39",
    "welfareSchemeId":"f4503a80-4eac-4aeb-ad45-d8d495c2b649"
}

