@url = http://localhost:5000
@memberId = 354c1baf-cad9-4392-bf85-7a843cc161c1
@districtId = 30BA1C7F-4BD7-43D9-9F62-07C377FEB667


###
# @name sign_in
POST {{url}}/users/sign-in
Content-Type: application/json

{
    "email": "mandalam-agent@admin.com",
    "password": "admin@123"
}

###
@accessToken = {{sign_in.response.body.$.accessToken}}


###
GET {{url}}/members

###
GET {{url}}/members/{{memberId}}

###
GET {{url}}/members/role
Authorization: Bearer {{accessToken}}

###
POST {{url}}/members
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "fullName": "Muhammed Rafi",
    "emiratesIdNumber": "784-1979-9625765-7",
    "emiratesIdExpiry": "2023-08-15",
    "emiratesIdFrontPage": null,
    "emiratesIdLastPage": null,
    "dateOfBirth": "1980-01-01",
    "mobileNumber": "0501234123",
    "email": "rafi.genius.cs@gmail.com",
    "passportNumber": "T453256",
    "passportExpiry": "2025-08-15",
    "passportFrontPage": null,
    "passportLastPage": null,
    "professionId" : "bda002ef-8948-42cc-8e62-259ac7dd6e1d",
    "qualificationId": "3b90e6f8-86f6-4065-a751-4142d43937c5",
    "bloodGroup": 0,
    "gender": 0,
    "photo": null,
    "houseName": "First Home",
    "addressInIndia": "First Street",
    "addressInDistrictId": "cf5e40d1-6f85-4540-9cb6-5ad7d7980141",
    "addressInMandalamId": "0cc0f6b5-89f4-437b-a449-a8f6069b40d8",
    "addressInPanchayatId": "f1d9bc5d-4556-4740-bc13-9a1acb8e88a3",
    "areaId": "97856452-46ee-4a51-a6c9-dfc065ec73dd",
    "panchayatId": "1bf4974b-b70a-4314-ab82-9adff66be809",
    "registeredOrganizationId": null,
    "welfareSchemeId": null
}
