@url = http://localhost:5000
@userId = 5e0a9aab-4c8e-4685-ace3-1e18f679de8f
@districtId = 30BA1C7F-4BD7-43D9-9F62-07C377FEB667



###
# @name sign_in
POST {{url}}/users/sign-in
Content-Type: application/json

{
    "email": "mandalam-agent@admin.com",
    "password": "admin@123"
}


###
@accessToken = {{sign_in.response.body.$.accessToken}}


POST {{url}}/ocr
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "FrontPageId": "5f81657d-ce3d-49e7-b468-1e140609b1fb",
    "LastPageId": "d89fc171-1170-4c64-8d96-d7e116622dbc",
    "UserId": null
}

###
POST {{url}}/ocr
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "FrontPageId": "5ddb8195-8f8b-4401-a9d5-b8e3748e9e19",
    "LastPageId": "afc94fdc-7896-44f9-a66e-2807d3cd92ca",
    "UserId": null
}