@url = http://localhost:5000
@userId = 5e0a9aab-4c8e-4685-ace3-1e18f679de8f
@districtId = 30BA1C7F-4BD7-43D9-9F62-07C377FEB667



###
# @name sign_in
POST {{url}}/users/sign-in
Content-Type: application/json

{
    "email": "mandalam-agent@admin.com",
    "password": "admin@123"
}


###
@accessToken = {{sign_in.response.body.$.accessToken}}


POST {{url}}/ocr
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "FrontPageId": "5f81657d-ce3d-49e7-b468-1e140609b1fb",
    "LastPageId": "d89fc171-1170-4c64-8d96-d7e116622dbc",
    "UserId": null
}

###
POST {{url}}/ocr
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "FrontPageId": "1ae9700f-44c3-4224-af0b-f703e0726102",
    "LastPageId": "23eee067-1096-4da6-9082-aa5e65c09aee",
    "UserId": null
}

###
POST {{url}}/ocr
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "FrontPageId": "92c73e1b-bea8-481d-b400-a24a55f24296",
    "LastPageId": "236e9a90-3586-4b20-8de2-54e810581e38",
    "UserId": null
}

###
POST {{url}}/ocr
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "FrontPageId": "48c715cc-d66d-4f01-8c7d-ff3eecbd6503",
    "LastPageId": "a0c80789-30f5-4301-8972-4f56b1c8b77f",
    "UserId": null
}

###
POST {{url}}/ocr
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "FrontPageId": "49e9d0c5-b344-40bd-a429-56c6079b359f",
    "LastPageId": "c1e353d4-603f-4789-8137-55701c4dc94d",
    "UserId": null
}

###
POST {{url}}/ocr
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "FrontPageId": "1c037a53-bfb3-4847-8899-4dace955d5a8",
    "LastPageId": "016f60b2-3c4f-474d-ac1f-373ea73b35fb",
    "UserId": null
}

###
POST {{url}}/ocr
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "FrontPageId": "784a55c3-93cf-43f9-9367-61fcd653f13b",
    "LastPageId": "882cedf0-89b9-4f19-b487-fb34e21c2343",
    "UserId": null
}

###
POST {{url}}/ocr
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "FrontPageId": "f1411f70-251b-4e30-9458-fb84c8199a5a",
    "LastPageId": "b8bb0598-2495-4e23-8e57-e7fd19117f4d",
    "UserId": null
}

###
POST {{url}}/ocr
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "FrontPageId": "ccf9246c-3727-46ca-8890-f183125944b9",
    "LastPageId": "28438750-b65a-4b5f-a540-9bcbf30a9f70",
    "UserId": null
}

###
POST {{url}}/ocr
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "FrontPageId": "e19c880c-2d6a-45b8-8538-cdd818c06e35",
    "LastPageId": "5a137d01-296e-41b0-9eb2-d4176df549db",
    "UserId": null
}

###
POST {{url}}/ocr
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "FrontPageId": "8e42a4bf-cb7f-4c57-a4ac-e2932fb3a68e",
    "LastPageId": "71746e4e-704d-44ae-b64a-79dd4665ccfa",
    "UserId": null
}

###
POST {{url}}/ocr
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "FrontPageId": "2d184280-9c27-4be4-b29f-58ef5e27118f",
    "LastPageId": "a5ad06e5-564d-438c-bb81-70be071af0f6",
    "UserId": null
}

### 21/08/2022
POST {{url}}/ocr
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "FrontPageId": "4a61e464-4647-4e01-ad65-dd4150a43aa2",
    "LastPageId": "ed9e727a-49a8-40b3-b7a8-f373c366685a",
    "UserId": null
}

### 
POST {{url}}/ocr
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "FrontPageId": "a38323a9-24f1-4c3a-8ef2-97628df3bad5",
    "LastPageId": "ed9e727a-49a8-40b3-b7a8-f373c366685a",
    "UserId": null
}