@url = http://localhost:5000
@professionId = c4613305-d19a-4719-931a-58d7d5853a41


###
# @name sign_in
POST {{url}}/users/sign-in
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin@123"
}

###
@accessToken = {{sign_in.response.body.$.accessToken}}


###
GET {{url}}/professions

###
GET {{url}}/professions/{{professionId}}

###
POST {{url}}/professions
Content-Type: application/json

{
    "name": "New profession"
}

###
PUT  {{url}}/professions/{{professionId}}
Content-Type: application/json

{
    "name": "New profession"
}

###
DELETE {{url}}/professions/{{professionId}}

