@url = http://localhost:5000
@registeredOrganizationId = c4613305-d19a-4719-931a-58d7d5853a41


###
# @name sign_in
POST {{url}}/users/sign-in
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin@123"
}

###
@accessToken = {{sign_in.response.body.$.accessToken}}


###
GET {{url}}/registeredOrganizations

###
GET {{url}}/registeredOrganizations/{{registeredOrganizationId}}

###
POST {{url}}/registeredOrganizations
Content-Type: application/json

{
    "name": "Malayalee Samajam"
}

###
PUT  {{url}}/registeredOrganizations/{{registeredOrganizationId}}
Content-Type: application/json

{
    "name": "New profession"
}

###
DELETE {{url}}/registeredOrganizations/{{registeredOrganizationId}}

