@url = http://localhost:5000
@userId = 5e0a9aab-4c8e-4685-ace3-1e18f679de8f
@districtId = 30BA1C7F-4BD7-43D9-9F62-07C377FEB667



###
# @name sign_in
POST {{url}}/users/sign-in
Content-Type: application/json

{
     "email": "admin@admin.com", 
    "password": "admin@123"
}

###
@accessToken = {{sign_in.response.body.$.accessToken}}


###
GET {{url}}/users

###
GET {{url}}/users/{{userId}}


###
GET {{url}}/users/me
Authorization: Bearer {{accessToken}}

###
GET {{url}}/users/role
Authorization: Bearer {{accessToken}}

###
POST {{url}}/users
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "fullName": "state-admin20",
    "email": "state-admin20@admin.com",
    "mobileNumber": "0554296326",
    "designation": "state-admin",
    "role": "state-admin",
    "cascadeId": "c4613305-d19a-4719-931a-58d7d5853a41",
    "isDisputeCommittee": false
}

###
GET {{url}}/users/role
Authorization: Bearer {{accessToken}}


###
PUT  {{url}}/users/{{userId}}
Content-Type: application/json

{
    "fullName": "Updated Name",
    "mobileNumber": "0501234123",
    "alternativeContactNumber": "0501234123",
    "designation": "state admin",
    "isDisputeCommittee": false
}

###
PUT  {{url}}/users/activate/{{userId}}

###
PUT  {{url}}/users/deactivate/{{userId}}

###
PUT  {{url}}/users/verify
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "email": "rafi.genius.cs@gmail.com",
    "verifyCode": "6251",
    "mobileLastFourDigit": "6326",
    "password": "admin@123",
    "confirmPassword": "admin@123"
}

###
PUT  {{url}}/users/forgetpassword
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "email": "mandalam-agent-arr@admin.com",
    "mobileLastFourDigit": "6326"
}

###
PUT  {{url}}/users/password
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "email": "rafi.genius.cs@gmail.com",
    "oldPassword": "6251",
    "password": "6326",
    "confirmPassword": "admin@123",
}

###
POST  {{url}}/users/resetpassword
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "userId": "cf66fb02-3f93-4a64-8edf-32196608f719",
    "email": "rafi.genius.cs1@gmail.com"
}



