@url = http://localhost:5000


###
# @name sign_in
POST {{url}}/users/sign-in
Content-Type: application/json

{
     "email": "dispute-committee@admin.com",
     "password": "X2QoUxRGQXFg/lv0NjvjGg=="
}

###
@accessToken = {{sign_in.response.body.$.accessToken}}


###
GET {{url}}/widgets
Authorization: Bearer {{accessToken}}
